spring:
  application:
    name: order
  rabbitmq:
    host: 192.168.1.102
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis:
#    host: 192.168.137.3
#    port: 6379
  jpa:
    show-sql: true
env: test
label: dev
girl:
  name: limei
